services:
  - type: web
    name: tehnomarket
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python check_deploy.py
    startCommand: gunicorn wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tehnomarket-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: FLASK_APP
        value: "wsgi.py"

databases:
  - name: tehnomarket-db
    plan: free
    postgresMajorVersion: 14 